const SHOP_DATA = [
  {
    id: 1,
    title: 'Chairs',
    routeName: 'chairs',
    items: [
      {
        id: 1,
        name: 'Chair 01',
        price: 25,
        imageUrl: '/imgs/sections/chairs/chair-1.jpg',
      },
      {
        id: 2,
        name: 'Chair 02',
        price: 18,
        imageUrl: '/imgs/sections/chairs/chair-2.jpg',
      },
      {
        id: 3,
        name: 'Chair 03',
        price: 35,
        imageUrl: '/imgs/sections/chairs/chair-3.jpg',
      },
      {
        id: 4,
        name: 'Chair 04',
        price: 25,
        imageUrl: '/imgs/sections/chairs/chair-4.jpg',
      },
      {
        id: 5,
        name: 'Chair 05',
        price: 18,
        imageUrl: '/imgs/sections/chairs/chair-5.jpg',
      },
      {
        id: 6,
        name: 'Chair 06',
        price: 14,
        imageUrl: '/imgs/sections/chairs/chair-6.jpg',
      },
      {
        id: 7,
        name: 'Chair 07',
        price: 18,
        imageUrl: '/imgs/sections/chairs/chair-7.jpg',
      },
      {
        id: 8,
        name: 'Chair 08',
        price: 14,
        imageUrl: '/imgs/sections/chairs/chair-8.jpg',
      },
      {
        id: 9,
        name: 'Chair 09',
        price: 16,
        imageUrl: '/imgs/sections/chairs/chair-9.jpg',
      },
      {
        id: 10,
        name: 'Chair 10',
        price: 140,
        imageUrl: '/imgs/sections/chairs/chair-10.jpg',
      },
      {
        id: 11,
        name: 'Chair 11',
        price: 75,
        imageUrl: '/imgs/sections/chairs/chair-11.jpg',
      },
      {
        id: 12,
        name: 'Chair 12',
        price: 63,
        imageUrl: '/imgs/sections/chairs/chair-8.jpg',
      },
    ],
  },
  {
    id: 2,
    title: 'Lamps',
    routeName: 'lamps',
    items: [
      {
        id: 16,
        name: 'lamp 01',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-1.jpg',
      },
      {
        id: 17,
        name: 'lamp 02',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-2.jpg',
      },
      {
        id: 18,
        name: 'lamp 03',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-3.jpg',
      },
      {
        id: 19,
        name: 'lamp 04',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-4.jpg',
      },
      {
        id: 20,
        name: 'lamp 05',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-5.jpg',
      },
      {
        id: 21,
        name: 'lamp 06',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-6.jpg',
      },
      {
        id: 22,
        name: 'lamp 07',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-7.jpg',
      },
      {
        id: 23,
        name: 'lamp 08',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-8.jpg',
      },
      {
        id: 24,
        name: 'lamp 09',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-9.jpg',
      },
      {
        id: 25,
        name: 'lamp 10',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-10.jpg',
      },
      {
        id: 26,
        name: 'lamp 11',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-11.jpg',
      },
      {
        id: 27,
        name: 'lamp 12',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-12.jpg',
      },
      {
        id: 28,
        name: 'lamp 13',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-13.jpg',
      },
      {
        id: 29,
        name: 'lamp 14',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-14.jpg',
      },
      {
        id: 30,
        name: 'lamp 15',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-15.jpg',
      },
      {
        id: 31,
        name: 'lamp 16',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-16.jpg',
      },
      {
        id: 32,
        name: 'lamp 17',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-17.jpg',
      },
      {
        id: 33,
        name: 'lamp 18',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-18.jpg',
      },
      {
        id: 34,
        name: 'lamp 19',
        price: 50,
        imageUrl: '/imgs/sections/lamps/lamp-5.jpg',
      },
    ],
  },
  {
    id: 3,
    title: 'Pillows',
    routeName: 'pillows',
    items: [
      {
        id: 36,
        name: 'pillow 01',
        price: 29,
        imageUrl: '/imgs/sections/pillows/pillow-1.jpg',
      },
      {
        id: 37,
        name: 'pillow 02',
        price: 29,
        imageUrl: '/imgs/sections/pillows/pillow-2.jpg',
      },
      {
        id: 38,
        name: 'pillow 03',
        price: 29,
        imageUrl: '/imgs/sections/pillows/pillow-3.jpg',
      },
      {
        id: 39,
        name: 'pillow 04',
        price: 29,
        imageUrl: '/imgs/sections/pillows/pillow-4.jpg',
      },
      {
        id: 40,
        name: 'pillow 05',
        price: 29,
        imageUrl: '/imgs/sections/pillows/pillow-5.jpg',
      },
      {
        id: 41,
        name: 'pillow 06',
        price: 29,
        imageUrl: '/imgs/sections/pillows/pillow-6.jpg',
      },
      {
        id: 42,
        name: 'pillow 07',
        price: 29,
        imageUrl: '/imgs/sections/pillows/pillow-7.jpg',
      },
      {
        id: 43,
        name: 'pillow 08',
        price: 29,
        imageUrl: '/imgs/sections/pillows/pillow-8.jpg',
      },
      {
        id: 44,
        name: 'pillow 09',
        price: 29,
        imageUrl: '/imgs/sections/pillows/pillow-9.jpg',
      },
    ],
  },
  {
    id: 4,
    title: 'Plant Pots',
    routeName: 'plant-pots',
    items: [
      {
        id: 55,
        name: 'plant pot 01',
        price: 52,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-1.jpg',
      },
      {
        id: 56,
        name: 'plant pot 02',
        price: 52,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-2.jpg',
      },
      {
        id: 57,
        name: 'plant pot 03',
        price: 52,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-3.jpg',
      },
      {
        id: 58,
        name: 'plant pot 04',
        price: 52,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-4.jpg',
      },
      {
        id: 59,
        name: 'plant pot 05',
        price: 52,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-5.jpg',
      },
      {
        id: 60,
        name: 'plant pot 06',
        price: 52,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-6.jpg',
      },
      {
        id: 61,
        name: 'plant pot 07',
        price: 52,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-7.jpg',
      },
      {
        id: 62,
        name: 'plant pot 08',
        price: 52,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-8.jpg',
      },
      {
        id: 63,
        name: 'plant pot 09',
        price: 52,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-9.jpg',
      },
      {
        id: 64,
        name: 'plant pot 10',
        price: 52,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-10.jpg',
      },
      {
        id: 65,
        name: 'plant pot 11',
        price: 52,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-11.jpg',
      },
      {
        id: 66,
        name: 'plant pot 12',
        price: 52,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-12.jpg',
      },
      {
        id: 67,
        name: 'plant pot 13',
        price: 52,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-13.jpg',
      },
      {
        id: 68,
        name: 'plant pot 14',
        price: 29,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-14.jpg',
      },
      {
        id: 69,
        name: 'plant pot 15',
        price: 29,
        imageUrl: '/imgs/sections/plant-pot/plant-pot-15.jpg',
      },
    ],
  },
  {
    id: 5,
    title: 'Shelfs',
    routeName: 'shelves',
    items: [
      {
        id: 71,
        name: 'shelf 01',
        price: 219,
        imageUrl: '/imgs/sections/shelves/shelf-1.jpg',
      },
      {
        id: 72,
        name: 'shelf 02',
        price: 219,
        imageUrl: '/imgs/sections/shelves/shelf-2.jpg',
      },
      {
        id: 73,
        name: 'shelf 03',
        price: 219,
        imageUrl: '/imgs/sections/shelves/shelf-3.jpg',
      },
      {
        id: 74,
        name: 'shelf 04',
        price: 219,
        imageUrl: '/imgs/sections/shelves/shelf-4.jpg',
      },
      {
        id: 75,
        name: 'shelf 05',
        price: 219,
        imageUrl: '/imgs/sections/shelves/shelf-5.jpg',
      },
      {
        id: 76,
        name: 'shelf 06',
        price: 219,
        imageUrl: '/imgs/sections/shelves/shelf-6.jpg',
      },
      {
        id: 77,
        name: 'shelf 07',
        price: 219,
        imageUrl: '/imgs/sections/shelves/shelf-7.jpg',
      },
      {
        id: 78,
        name: 'shelf 08',
        price: 219,
        imageUrl: '/imgs/sections/shelves/shelf-8.jpg',
      },
      {
        id: 79,
        name: 'shelf 09',
        price: 219,
        imageUrl: '/imgs/sections/shelves/shelf-9.jpg',
      },
      {
        id: 80,
        name: 'shelf 10',
        price: 219,
        imageUrl: '/imgs/sections/shelves/shelf-10.jpg',
      },
      {
        id: 81,
        name: 'shelf 11',
        price: 219,
        imageUrl: '/imgs/sections/shelves/shelf-11.jpg',
      },
      {
        id: 82,
        name: 'shelf 12',
        price: 219,
        imageUrl: '/imgs/sections/shelves/shelf-12.jpg',
      },
      {
        id: 83,
        name: 'shelf 13',
        price: 219,
        imageUrl: '/imgs/sections/shelves/shelf-13.jpg',
      },
    ],
  },
  {
    id: 6,
    title: 'Side Tables',
    routeName: 'side-tables',
    items: [
      {
        id: 87,
        name: 'side table 01',
        price: 166,
        imageUrl: '/imgs/sections/side-tables/side-tables-1.jpg',
      },
      {
        id: 88,
        name: 'side table 02',
        price: 166,
        imageUrl: '/imgs/sections/side-tables/side-tables-2.jpg',
      },
      {
        id: 89,
        name: 'side table 03',
        price: 166,
        imageUrl: '/imgs/sections/side-tables/side-tables-3.jpg',
      },
      {
        id: 90,
        name: 'side table 04',
        price: 166,
        imageUrl: '/imgs/sections/side-tables/side-tables-4.jpg',
      },
      {
        id: 91,
        name: 'side table 05',
        price: 166,
        imageUrl: '/imgs/sections/side-tables/side-tables-5.jpg',
      },
      {
        id: 92,
        name: 'side table 06',
        price: 166,
        imageUrl: '/imgs/sections/side-tables/side-tables-6.jpg',
      },
      {
        id: 93,
        name: 'side table 07',
        price: 166,
        imageUrl: '/imgs/sections/side-tables/side-tables-7.jpg',
      },
      {
        id: 94,
        name: 'side table 08',
        price: 166,
        imageUrl: '/imgs/sections/side-tables/side-tables-8.jpg',
      },
      {
        id: 95,
        name: 'side table 09',
        price: 166,
        imageUrl: '/imgs/sections/side-tables/side-tables-9.jpg',
      },
      {
        id: 96,
        name: 'side table 10',
        price: 166,
        imageUrl: '/imgs/sections/side-tables/side-tables-10.jpg',
      },
      {
        id: 97,
        name: 'side table 11',
        price: 166,
        imageUrl: '/imgs/sections/side-tables/side-tables-11.jpg',
      },
    ],
  },
  {
    id: 7,
    title: 'Sofas',
    routeName: 'sofas',
    items: [
      {
        id: 104,
        name: 'sofa 01',
        price: 599,
        imageUrl: '/imgs/sections/sofas/sofa-1.jpg',
      },
      {
        id: 105,
        name: 'sofa 02',
        price: 599,
        imageUrl: '/imgs/sections/sofas/sofa-2.jpg',
      },
      {
        id: 106,
        name: 'sofa 03',
        price: 599,
        imageUrl: '/imgs/sections/sofas/sofa-3.jpg',
      },
      {
        id: 107,
        name: 'sofa 04',
        price: 599,
        imageUrl: '/imgs/sections/sofas/sofa-4.jpg',
      },
      {
        id: 108,
        name: 'sofa 05',
        price: 599,
        imageUrl: '/imgs/sections/sofas/sofa-5.jpg',
      },
      {
        id: 109,
        name: 'sofa 06',
        price: 599,
        imageUrl: '/imgs/sections/sofas/sofa-6.jpg',
      },
      {
        id: 110,
        name: 'sofa 07',
        price: 599,
        imageUrl: '/imgs/sections/sofas/sofa-7.jpg',
      },
      {
        id: 111,
        name: 'sofa 08',
        price: 599,
        imageUrl: '/imgs/sections/sofas/sofa-8.jpg',
      },
      {
        id: 112,
        name: 'sofa 09',
        price: 599,
        imageUrl: '/imgs/sections/sofas/sofa-9.jpg',
      },
      {
        id: 113,
        name: 'sofa 10',
        price: 599,
        imageUrl: '/imgs/sections/sofas/sofa-10.jpg',
      },
      {
        id: 114,
        name: 'sofa 11',
        price: 599,
        imageUrl: '/imgs/sections/sofas/sofa-11.jpg',
      },
      {
        id: 115,
        name: 'sofa 12',
        price: 599,
        imageUrl: '/imgs/sections/sofas/sofa-12.jpg',
      },
      {
        id: 116,
        name: 'sofa 13',
        price: 599,
        imageUrl: '/imgs/sections/sofas/sofa-13.jpg',
      },
    ],
  },
  {
    id: 8,
    title: 'Beds',
    routeName: 'beds',
    items: [
      {
        id: 123,
        name: 'bed 01',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-1.jpg',
      },
      {
        id: 124,
        name: 'bed 02',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-2.jpg',
      },
      {
        id: 125,
        name: 'bed 03',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-3.jpg',
      },
      {
        id: 126,
        name: 'bed 04',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-4.jpg',
      },
      {
        id: 127,
        name: 'bed 05',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-5.jpg',
      },
      {
        id: 128,
        name: 'bed 06',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-6.jpg',
      },
      {
        id: 129,
        name: 'bed 07',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-7.jpg',
      },
      {
        id: 130,
        name: 'bed 08',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-8.jpg',
      },
      {
        id: 131,
        name: 'bed 09',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-9.jpg',
      },
      {
        id: 132,
        name: 'bed 10',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-10.jpg',
      },
      {
        id: 133,
        name: 'bed 11',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-11.jpg',
      },
      {
        id: 134,
        name: 'bed 12',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-12.jpg',
      },
      {
        id: 135,
        name: 'bed 13',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-13.jpg',
      },
      {
        id: 136,
        name: 'bed 14',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-14.jpg',
      },
      {
        id: 137,
        name: 'bed 15',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-15.jpg',
      },
      {
        id: 138,
        name: 'bed 16',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-16.jpg',
      },
      {
        id: 139,
        name: 'bed 17',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-17.jpg',
      },
      {
        id: 140,
        name: 'bed 18',
        price: 450,
        imageUrl: '/imgs/sections/beds/bed-18.jpg',
      },
    ],
  },
  {
    id: 9,
    title: 'Home Deco',
    routeName: 'home-deco',
    items: [
      {
        id: 142,
        name: 'home deco 01',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-1.jpg',
      },
      {
        id: 143,
        name: 'home deco 02',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-2.jpg',
      },
      {
        id: 144,
        name: 'home deco 03',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-3.jpg',
      },
      {
        id: 145,
        name: 'home deco 04',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-4.jpg',
      },
      {
        id: 146,
        name: 'home deco 05',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-5.jpg',
      },
      {
        id: 147,
        name: 'home deco 06',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-6.jpg',
      },
      {
        id: 148,
        name: 'home deco 07',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-7.jpg',
      },
      {
        id: 149,
        name: 'home deco 08',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-8.jpg',
      },
      {
        id: 150,
        name: 'home deco 09',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-9.jpg',
      },
      {
        id: 151,
        name: 'home deco 10',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-10.jpg',
      },
      {
        id: 152,
        name: 'home deco 11',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-11.jpg',
      },
      {
        id: 153,
        name: 'home deco 12',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-12.jpg',
      },
      {
        id: 154,
        name: 'home deco 13',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-13.jpg',
      },
      {
        id: 155,
        name: 'home deco 14',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-14.jpg',
      },
      {
        id: 156,
        name: 'home deco 15',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-15.jpg',
      },
      {
        id: 157,
        name: 'home deco 16',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-16.jpg',
      },
      {
        id: 158,
        name: 'home deco 17',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-17.jpg',
      },
      {
        id: 159,
        name: 'home deco 18',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-18.jpg',
      },
      {
        id: 160,
        name: 'home deco 19',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-19.jpg',
      },
      {
        id: 161,
        name: 'home deco 20',
        price: 49,
        imageUrl: '/imgs/sections/home-deco/home-deco-20.jpg',
      },
      // {
      //   id: 162,
      //   name: 'home deco 21',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 163,
      //   name: 'home deco 22',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 164,
      //   name: 'home deco 23',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 165,
      //   name: 'home deco 24',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 166,
      //   name: 'home deco 25',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 167,
      //   name: 'home deco 26',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 1,
      //   name: 'home deco 27',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 168,
      //   name: 'home deco 28',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 169,
      //   name: 'home deco 29',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 170,
      //   name: 'home deco 30',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 171,
      //   name: 'home deco 31',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 172,
      //   name: 'home deco 32',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 173,
      //   name: 'home deco 33',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 174,
      //   name: 'home deco 34',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 175,
      //   name: 'home deco 35',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 176,
      //   name: 'home deco 36',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 177,
      //   name: 'home deco 37',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 178,
      //   name: 'home deco 38',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
      // {
      //   id: 179,
      //   name: 'home deco 39',
      //   price: 49,
      //   imageUrl: '/imgs/sections/home-deco/home-deco-homepage.jpg',
      // },
    ],
  },
]

export default SHOP_DATA
